먼저 자료를 확인해보면 종속변수에 해당하는 품종이 범주형 데이터에 해당함을 알 수 있다.

이런 범주형 데이터는 수식에 사용할 수 없어서, 형태를 바꿔주어야 한다.

In [5]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

# 1.과거의 데이터를 준비
dir = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(dir)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

위에서 언급한 범주형 데이터를 1과 0의 형태로 바꿔주는걸 원 핫 인코딩이라고 한다.

판다스에서는 범주형 데이터를 아래와 같은 코드로 

데이터 내의 범주형 변수만 골라내어
원 핫 인코딩 된 결과를 반환해준다.

In [8]:
# 원핫인코딩
iris = pd.get_dummies(iris)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [9]:
# 종속변수, 독립변수
inde = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
de = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(inde.shape, de.shape)

(150, 4) (150, 3)


(Activation) 활성화 함수 분류 문제에서 softmax의 경우 
전체 확률의 합계가 1이 되도록 도와준다.

또한 이렇게 결과를 최솟값은 0 최댓값은 1로 만들고 싶을때

아래의 구조에서 수식을 하나 써보면

y1 = softmax(w11x11 + w12x12 + w13x13 + w14+x14 + b1)

y1 은 softmax함수에 의해 0과 1의 결과를 가질 수 있다.

In [10]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [11]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(inde, de, epochs=1000, verbose=0)
model.fit(inde, de, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1568 - accuracy: 0.9667
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1565 - accuracy: 0.9667
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1560 - accuracy: 0.9667
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1567 - accuracy: 0.9733
Epoch 5/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1562 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1560 - accuracy: 0.9733
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1557 - accuracy: 0.9667
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1557 - accuracy: 0.9667
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1559 - accuracy: 0.9667
Epoch 10/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1554 - accuracy: 0.9733


In [12]:
# 4. 모델을 이용
# 맨 처음 데이터 5개
print(model.predict(inde[:5]))
print(de[:5])

[[9.9922407e-01 7.7587843e-04 2.9285196e-08]
 [9.9737692e-01 2.6228921e-03 2.9565774e-07]
 [9.9847478e-01 1.5251166e-03 1.1934829e-07]
 [9.9616277e-01 3.8367878e-03 5.3081823e-07]
 [9.9930847e-01 6.9149665e-04 2.3457927e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [13]:
# 맨 마지막 데이터 5개
print(model.predict(inde[-5:]))
print(de[-5:]) 

[[2.3616190e-07 1.2228394e-01 8.7771589e-01]
 [7.8166954e-07 1.6284755e-01 8.3715165e-01]
 [1.3530762e-06 2.3733898e-01 7.6265967e-01]
 [1.8983685e-07 1.2707734e-01 8.7292242e-01]
 [3.1190496e-06 2.9866123e-01 7.0133567e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [14]:
# weights & bias 출력
print(model.get_weights())

[array([[ 0.9294032 ,  0.00972285, -0.7908548 ],
       [ 2.8809483 ,  0.80904454, -1.0588905 ],
       [-3.5905342 , -0.46191832,  1.0528747 ],
       [-5.0897703 , -0.8684015 ,  2.3441648 ]], dtype=float32), array([ 1.5369452,  1.0939034, -1.2332702], dtype=float32)]
