In [8]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

# 1.과거의 데이터를 준비
dir = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(dir)

In [9]:
# 원핫인코딩
iris = pd.get_dummies(iris)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [10]:
# 종속변수, 독립변수
inde = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
de = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(inde.shape, de.shape)

(150, 4) (150, 3)


In [11]:
# 2. 모델의 구조 만들기
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [12]:
# 모델 구조 확인
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_6 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_7 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [13]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(inde, de, epochs=2000, verbose=0)
model.fit(inde, de, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0444 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0422 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0482 - accuracy: 0.9733
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0464 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0442 - accuracy: 0.9867
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0474 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0491 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0444 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0457 - accuracy: 0.9867
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0408 - accuracy: 0.9867


In [15]:
# 4. 모델을 이용합니다
print(model.predict(inde[:5]))
print(de[:5])

[[1.0000000e+00 4.7989888e-15 1.0986112e-09]
 [1.0000000e+00 8.8633385e-14 7.2071260e-09]
 [1.0000000e+00 7.9659092e-14 6.2333108e-09]
 [1.0000000e+00 3.1547107e-12 5.0412332e-08]
 [1.0000000e+00 9.2804767e-15 1.5129332e-09]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
