In [2]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

# 1.과거의 데이터를 준비
dir = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(dir) 

In [3]:
# 원핫인코딩
iris = pd.get_dummies(iris) 
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [4]:
# 종속변수, 독립변수
inde = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
de = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(inde.shape, de.shape)

(150, 4) (150, 3)


In [5]:
# 2. 모델의 구조를 BatchNormalization layer를 사용하여 만든다.
X = tf.keras.layers.Input(shape=[4])
 
H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
 
H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
 
H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
 
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [8]:
# 3.데이터로 모델을 학습(FIT)
model.fit(inde, de, epochs=1000, verbose=0)
model.fit(inde, de, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0309 - accuracy: 0.9867
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0345 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0481 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0211 - accuracy: 0.9933
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0184 - accuracy: 0.9933
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0493 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1660 - accuracy: 0.9467
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0162 - accuracy: 1.0000
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0548 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0142 - accuracy: 1.0000


In [9]:
# 4. 모델을 이용
print(model.predict(inde[:5]))
print(de[:5])

[[1.0000000e+00 1.9424828e-08 2.4529818e-08]
 [1.0000000e+00 4.4374659e-08 7.4073347e-10]
 [1.0000000e+00 6.1883783e-09 2.6144382e-09]
 [9.9999988e-01 1.1124467e-07 1.7611336e-08]
 [1.0000000e+00 1.5228991e-08 3.8401968e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
